---
meta:
  name:    vault-broker
  release: Vault Broker
  target:  pipes
  url:     https://pipes.starkandwayne.com

  go:
    force_static_binary: true

  aws:
    access_key: ((cfcommunity.access))
    secret_key: ((cfcommunity.secret))

  github:
    owner:  cloudfoundry-community
    repo:   vault-broker
    private_key:  ((github.private-key))
    access_token: ((github.access-token))

  slack:
    webhook: ((slack.webhook))
    channel: '#vault'
