---
meta:
  name:    vault-broker
  release: Vault Broker
  target:  sw
  url:     https://ci.starkandwayne.com

  go:
    force_static_binary: true

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  github:
    owner:  cloudfoundry-community
    repo:   vault-broker
    private_key:  (( vault "secret/pipelines/vault-broker/github:private" ))
    access_token: (( vault "secret/pipelines/vault-broker/github:token" ))

  slack:
    webhook: (( vault "secret/pipelines/vault-broker/slack:webhook" ))
    channel: '#vault'
